version: '2'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./www:/var/www
            - ./etc/nginx/conf.d:/etc/nginx/conf.d
            - ./etc/nginx/conf:/etc/nginx/conf
            - ./etc/nginx/cert:/etc/nginx/cert
            - /c/Users/Docker/webot/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - develop
    php:
        image: php:fpm
        ports:
            - "9000:9000"
        volumes:
            - ./www:/var/www
            - /c/Users/Docker/webot/etc:/usr/local/etc
        networks:
            - develop

networks:
    develop:
        driver: bridge
